#!/bin/bash
cd scripts
git clone https://github.com/DmitryUlyanov/Multicore-TSNE.git
cd Multicore-TSNE
pip install .

jupyter nbextension enable --py --user widgetsnbextension

jupyter nbextension install --py --user nbtools
jupyter nbextension enable --py --user nbtools

jupyter nbextension install --py --user genepattern
jupyter nbextension enable --py --user genepattern
jupyter serverextension enable --py --user genepattern
